#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=0:25:00
#PBS -N app-decimatemesh
#PBS -V



if [ $ENV == "IUHPC" ]; then
	module unload python
	if [ $HPC == "KARST" ]; then
		module load anaconda2
	fi
	if [ $HPC == "CARBONATE" ]; then
		module load anaconda/python2.7/4.3.1
	fi	
fi

source activate mindboggle

rm -rf surfaces


echo "counting files"
NUMFILES=`$SERVICE_DIR/numfiles.py`
echo "there are $NUMFILES files" 


echo "starting main"
python $SERVICE_DIR/main.py > stdout.log 2> stderr.log


#check for output files

count=$(ls surfaces/* | wc -l)

if [ "$count" == "$NUMFILES" ] 
then
	echo 0 > finished
else
	echo "files missing"
	echo 1 > finished
	exit 1
fi

