#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=0:25:00
#PBS -N app-decimatemesh
#PBS -V



#if [ $ENV == "IUHPC" ]; then
#	module unload python
#	if [ $HPC == "KARST" ]; then
#		module load anaconda2
#	fi
#	if [ $HPC == "CARBONATE" ]; then
#		module load anaconda/python2.7/4.3.1
#	fi	
#fi

#source activate mindboggle

rm -rf surfaces
rm -f finished

module load singularity 2> /dev/null

echo "counting files"
NUMFILES=`./numfiles.py`
echo "there are $NUMFILES files" 


echo "starting main"
#python ./main.py > stdout.log 2> stderr.log
singularity exec -e docker://lukin0110/docker-vtk-python ./main.py


#check for output files

count=$(ls surfaces/* | wc -l)

if [ "$count" == "$NUMFILES" ] 
then
	echo 0 > finished
else
	echo "files missing"
	echo 1 > finished
	exit 1
fi

